import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import NavBar from "@/components/NavBar";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link
          rel="icon"
          href="/logo.svg"
          type="image/svg+xml"
        />
      </Head>
      <body className={cn(inter.className, "bg-[rgb(21,23,25)] antialiased")}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
